//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oclockvn.Extensions.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("oclockvn.Extensions.i18n.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngày hôm qua.
        /// </summary>
        public static string TimeAgo_Day {
            get {
                return ResourceManager.GetString("TimeAgo_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ngày trước.
        /// </summary>
        public static string TimeAgo_Days {
            get {
                return ResourceManager.GetString("TimeAgo_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 giờ trước.
        /// </summary>
        public static string TimeAgo_Hour {
            get {
                return ResourceManager.GetString("TimeAgo_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} giờ trước.
        /// </summary>
        public static string TimeAgo_Hours {
            get {
                return ResourceManager.GetString("TimeAgo_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 phút trước.
        /// </summary>
        public static string TimeAgo_Minute {
            get {
                return ResourceManager.GetString("TimeAgo_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phút trước.
        /// </summary>
        public static string TimeAgo_Minutes {
            get {
                return ResourceManager.GetString("TimeAgo_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 tháng trước.
        /// </summary>
        public static string TimeAgo_Month {
            get {
                return ResourceManager.GetString("TimeAgo_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tháng trước.
        /// </summary>
        public static string TimeAgo_Months {
            get {
                return ResourceManager.GetString("TimeAgo_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vừa xong.
        /// </summary>
        public static string TimeAgo_Second {
            get {
                return ResourceManager.GetString("TimeAgo_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} giây trước.
        /// </summary>
        public static string TimeAgo_Seconds {
            get {
                return ResourceManager.GetString("TimeAgo_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} năm trước.
        /// </summary>
        public static string TimeAgo_Year {
            get {
                return ResourceManager.GetString("TimeAgo_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} năm trước.
        /// </summary>
        public static string TimeAgo_Years {
            get {
                return ResourceManager.GetString("TimeAgo_Years", resourceCulture);
            }
        }
    }
}
